package com.simba.sqlengine.executor.conversions;

import com.simba.dsi.dataengine.interfaces.IColumn;
import com.simba.dsi.dataengine.utilities.TypeMetadata;
import com.simba.dsi.dataengine.utilities.TypeUtilities;
import com.simba.sqlengine.exceptions.SQLEngineExceptionFactory;
import com.simba.support.Pair;
import com.simba.support.exceptions.ErrorException;
import java.util.HashMap;
import java.util.Map;

public class SqlConverterGenerator
{
  private Map<Pair<Integer, Integer>, ISqlConverterFactory> m_converterFactoryTable;
  
  public SqlConverterGenerator()
  {
    init();
  }
  
  public ISqlConverter createConverter(IColumn paramIColumn1, IColumn paramIColumn2)
    throws ErrorException
  {
    int i = paramIColumn1.getTypeMetadata().getType();
    int j = paramIColumn2.getTypeMetadata().getType();
    Pair localPair = new Pair(Integer.valueOf(i), Integer.valueOf(j));
    ISqlConverterFactory localISqlConverterFactory = (ISqlConverterFactory)this.m_converterFactoryTable.get(localPair);
    if (null == localISqlConverterFactory) {
      throw SQLEngineExceptionFactory.conversionNotSupported(TypeUtilities.sqlTypeToString((short)i), TypeUtilities.sqlTypeToString((short)j));
    }
    return localISqlConverterFactory.createSqlConverter(paramIColumn1, paramIColumn2);
  }
  
  public ISqlConverter createCustomConverter(IColumn paramIColumn1, IColumn paramIColumn2)
    throws ErrorException
  {
    return null;
  }
  
  private void init()
  {
    this.m_converterFactoryTable = new HashMap();
    SqlBinaryTypeConverterFactory localSqlBinaryTypeConverterFactory = new SqlBinaryTypeConverterFactory();
    SqlCharTypeConverterFactory localSqlCharTypeConverterFactory = new SqlCharTypeConverterFactory();
    SqlDateTimeConverterFactory localSqlDateTimeConverterFactory = new SqlDateTimeConverterFactory();
    SqlExactNumberConverterFactory localSqlExactNumberConverterFactory = new SqlExactNumberConverterFactory();
    SqlApproxNumConverterFactory localSqlApproxNumConverterFactory = new SqlApproxNumConverterFactory();
    SqlIntegralConverterFactory localSqlIntegralConverterFactory = new SqlIntegralConverterFactory();
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-2), Integer.valueOf(-2)), localSqlBinaryTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-2), Integer.valueOf(-3)), localSqlBinaryTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-2), Integer.valueOf(-4)), localSqlBinaryTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-3), Integer.valueOf(-2)), localSqlBinaryTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-3), Integer.valueOf(-3)), localSqlBinaryTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-3), Integer.valueOf(-4)), localSqlBinaryTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-4), Integer.valueOf(-2)), localSqlBinaryTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-4), Integer.valueOf(-3)), localSqlBinaryTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-4), Integer.valueOf(-4)), localSqlBinaryTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-5), Integer.valueOf(-5)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(4), Integer.valueOf(-5)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-6), Integer.valueOf(-5)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(5), Integer.valueOf(-5)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(1), Integer.valueOf(-5)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(12), Integer.valueOf(-5)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-1), Integer.valueOf(-5)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-8), Integer.valueOf(-5)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-9), Integer.valueOf(-5)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-10), Integer.valueOf(-5)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(1), Integer.valueOf(-7)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(12), Integer.valueOf(-7)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-1), Integer.valueOf(-7)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-8), Integer.valueOf(-7)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-9), Integer.valueOf(-7)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-10), Integer.valueOf(-7)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(4), Integer.valueOf(-7)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(5), Integer.valueOf(-7)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-6), Integer.valueOf(-7)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-5), Integer.valueOf(-7)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(4), Integer.valueOf(16)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(5), Integer.valueOf(16)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-6), Integer.valueOf(16)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-5), Integer.valueOf(16)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(1), Integer.valueOf(16)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(12), Integer.valueOf(16)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-1), Integer.valueOf(16)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-8), Integer.valueOf(16)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-9), Integer.valueOf(16)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-10), Integer.valueOf(16)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(1), Integer.valueOf(91)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(12), Integer.valueOf(91)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-1), Integer.valueOf(91)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-8), Integer.valueOf(91)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-9), Integer.valueOf(91)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-10), Integer.valueOf(91)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(1), Integer.valueOf(8)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(12), Integer.valueOf(8)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-1), Integer.valueOf(8)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-8), Integer.valueOf(8)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-9), Integer.valueOf(8)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-10), Integer.valueOf(8)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-5), Integer.valueOf(8)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(1), Integer.valueOf(6)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(12), Integer.valueOf(6)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-1), Integer.valueOf(6)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-8), Integer.valueOf(6)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-9), Integer.valueOf(6)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-10), Integer.valueOf(6)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-5), Integer.valueOf(6)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(1), Integer.valueOf(-11)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(12), Integer.valueOf(-11)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-1), Integer.valueOf(-11)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-8), Integer.valueOf(-11)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-9), Integer.valueOf(-11)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-10), Integer.valueOf(-11)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-5), Integer.valueOf(4)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(4), Integer.valueOf(4)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-6), Integer.valueOf(4)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(5), Integer.valueOf(4)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(1), Integer.valueOf(4)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(12), Integer.valueOf(4)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-1), Integer.valueOf(4)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-8), Integer.valueOf(4)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-9), Integer.valueOf(4)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-10), Integer.valueOf(4)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(1), Integer.valueOf(7)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(12), Integer.valueOf(7)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-1), Integer.valueOf(7)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-8), Integer.valueOf(7)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-9), Integer.valueOf(7)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-10), Integer.valueOf(7)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(4), Integer.valueOf(7)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-5), Integer.valueOf(7)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-5), Integer.valueOf(5)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(4), Integer.valueOf(5)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-6), Integer.valueOf(5)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(5), Integer.valueOf(5)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(1), Integer.valueOf(5)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(12), Integer.valueOf(5)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-1), Integer.valueOf(5)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-8), Integer.valueOf(5)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-9), Integer.valueOf(5)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-10), Integer.valueOf(5)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(1), Integer.valueOf(92)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(12), Integer.valueOf(92)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-1), Integer.valueOf(92)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-8), Integer.valueOf(92)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-9), Integer.valueOf(92)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-10), Integer.valueOf(92)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-5), Integer.valueOf(-6)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(4), Integer.valueOf(-6)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-6), Integer.valueOf(-6)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(5), Integer.valueOf(-6)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(1), Integer.valueOf(-6)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(12), Integer.valueOf(-6)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-1), Integer.valueOf(-6)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-8), Integer.valueOf(-6)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-9), Integer.valueOf(-6)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-10), Integer.valueOf(-6)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(1), Integer.valueOf(93)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(12), Integer.valueOf(93)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-1), Integer.valueOf(93)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-8), Integer.valueOf(93)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-9), Integer.valueOf(93)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-10), Integer.valueOf(93)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(1), Integer.valueOf(1)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(12), Integer.valueOf(1)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-1), Integer.valueOf(1)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-8), Integer.valueOf(1)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-9), Integer.valueOf(1)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-10), Integer.valueOf(1)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(1), Integer.valueOf(12)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(12), Integer.valueOf(12)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-1), Integer.valueOf(12)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-8), Integer.valueOf(12)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-9), Integer.valueOf(12)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-10), Integer.valueOf(12)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(1), Integer.valueOf(-1)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(12), Integer.valueOf(-1)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-1), Integer.valueOf(-1)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-8), Integer.valueOf(-1)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-9), Integer.valueOf(-1)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-10), Integer.valueOf(-1)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(1), Integer.valueOf(-8)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(12), Integer.valueOf(-8)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-1), Integer.valueOf(-8)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-8), Integer.valueOf(-8)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-9), Integer.valueOf(-8)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-10), Integer.valueOf(-8)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(1), Integer.valueOf(-9)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(12), Integer.valueOf(-9)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-1), Integer.valueOf(-9)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-8), Integer.valueOf(-9)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-9), Integer.valueOf(-9)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-10), Integer.valueOf(-9)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(1), Integer.valueOf(-10)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(12), Integer.valueOf(-10)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-1), Integer.valueOf(-10)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-8), Integer.valueOf(-10)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-9), Integer.valueOf(-10)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-10), Integer.valueOf(-10)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(91), Integer.valueOf(93)), localSqlDateTimeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(93), Integer.valueOf(91)), localSqlDateTimeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(93), Integer.valueOf(92)), localSqlDateTimeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(92), Integer.valueOf(92)), localSqlDateTimeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(93), Integer.valueOf(93)), localSqlDateTimeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(92), Integer.valueOf(93)), localSqlDateTimeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(3), Integer.valueOf(8)), localSqlExactNumberConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(3), Integer.valueOf(6)), localSqlExactNumberConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(3), Integer.valueOf(-5)), localSqlExactNumberConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(3), Integer.valueOf(4)), localSqlExactNumberConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(3), Integer.valueOf(5)), localSqlExactNumberConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(3), Integer.valueOf(-6)), localSqlExactNumberConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(3), Integer.valueOf(7)), localSqlExactNumberConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(3), Integer.valueOf(-7)), localSqlExactNumberConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(3), Integer.valueOf(16)), localSqlExactNumberConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(2), Integer.valueOf(8)), localSqlExactNumberConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(2), Integer.valueOf(6)), localSqlExactNumberConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(2), Integer.valueOf(-5)), localSqlExactNumberConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(2), Integer.valueOf(4)), localSqlExactNumberConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(2), Integer.valueOf(5)), localSqlExactNumberConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(2), Integer.valueOf(7)), localSqlExactNumberConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(2), Integer.valueOf(-6)), localSqlExactNumberConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(2), Integer.valueOf(-7)), localSqlExactNumberConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(2), Integer.valueOf(16)), localSqlExactNumberConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-5), Integer.valueOf(2)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-7), Integer.valueOf(2)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(16), Integer.valueOf(2)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-6), Integer.valueOf(2)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(7), Integer.valueOf(2)), localSqlApproxNumConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(2), Integer.valueOf(2)), localSqlExactNumberConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(5), Integer.valueOf(2)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(4), Integer.valueOf(2)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(6), Integer.valueOf(2)), localSqlApproxNumConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(8), Integer.valueOf(2)), localSqlApproxNumConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(3), Integer.valueOf(2)), localSqlExactNumberConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(1), Integer.valueOf(2)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(12), Integer.valueOf(2)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-1), Integer.valueOf(2)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-8), Integer.valueOf(2)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-9), Integer.valueOf(2)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-10), Integer.valueOf(2)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-5), Integer.valueOf(3)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-7), Integer.valueOf(3)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(16), Integer.valueOf(3)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-6), Integer.valueOf(3)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(5), Integer.valueOf(3)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(2), Integer.valueOf(3)), localSqlExactNumberConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(4), Integer.valueOf(3)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(7), Integer.valueOf(3)), localSqlApproxNumConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(6), Integer.valueOf(3)), localSqlApproxNumConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(8), Integer.valueOf(3)), localSqlApproxNumConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(3), Integer.valueOf(3)), localSqlExactNumberConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(2), Integer.valueOf(3)), localSqlExactNumberConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(7), Integer.valueOf(-5)), localSqlApproxNumConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(6), Integer.valueOf(-5)), localSqlApproxNumConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(8), Integer.valueOf(-5)), localSqlApproxNumConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(8), Integer.valueOf(7)), localSqlApproxNumConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(7), Integer.valueOf(4)), localSqlApproxNumConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(6), Integer.valueOf(4)), localSqlApproxNumConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(8), Integer.valueOf(4)), localSqlApproxNumConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(7), Integer.valueOf(5)), localSqlApproxNumConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(6), Integer.valueOf(5)), localSqlApproxNumConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(8), Integer.valueOf(5)), localSqlApproxNumConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(7), Integer.valueOf(-6)), localSqlApproxNumConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(6), Integer.valueOf(-6)), localSqlApproxNumConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(8), Integer.valueOf(-6)), localSqlApproxNumConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(1), Integer.valueOf(3)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(12), Integer.valueOf(3)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-1), Integer.valueOf(3)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-8), Integer.valueOf(3)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-9), Integer.valueOf(3)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-10), Integer.valueOf(3)), localSqlCharTypeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(4), Integer.valueOf(1)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-6), Integer.valueOf(1)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(5), Integer.valueOf(1)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-5), Integer.valueOf(1)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(8), Integer.valueOf(1)), localSqlApproxNumConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(6), Integer.valueOf(1)), localSqlApproxNumConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(7), Integer.valueOf(1)), localSqlApproxNumConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(91), Integer.valueOf(1)), localSqlDateTimeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(92), Integer.valueOf(1)), localSqlDateTimeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(93), Integer.valueOf(1)), localSqlDateTimeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(2), Integer.valueOf(1)), localSqlExactNumberConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(3), Integer.valueOf(1)), localSqlExactNumberConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-7), Integer.valueOf(1)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(16), Integer.valueOf(1)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(4), Integer.valueOf(12)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-6), Integer.valueOf(12)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(5), Integer.valueOf(12)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-5), Integer.valueOf(12)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(8), Integer.valueOf(12)), localSqlApproxNumConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(6), Integer.valueOf(12)), localSqlApproxNumConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(7), Integer.valueOf(12)), localSqlApproxNumConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(91), Integer.valueOf(12)), localSqlDateTimeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(92), Integer.valueOf(12)), localSqlDateTimeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(93), Integer.valueOf(12)), localSqlDateTimeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(2), Integer.valueOf(12)), localSqlExactNumberConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(3), Integer.valueOf(12)), localSqlExactNumberConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-7), Integer.valueOf(12)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(16), Integer.valueOf(12)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(4), Integer.valueOf(-1)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-6), Integer.valueOf(-1)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(5), Integer.valueOf(-1)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-5), Integer.valueOf(-1)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(8), Integer.valueOf(-1)), localSqlApproxNumConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(6), Integer.valueOf(-1)), localSqlApproxNumConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(7), Integer.valueOf(-1)), localSqlApproxNumConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(91), Integer.valueOf(-1)), localSqlDateTimeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(92), Integer.valueOf(-1)), localSqlDateTimeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(93), Integer.valueOf(-1)), localSqlDateTimeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(2), Integer.valueOf(-1)), localSqlExactNumberConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(3), Integer.valueOf(-1)), localSqlExactNumberConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-7), Integer.valueOf(-1)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(16), Integer.valueOf(-1)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(4), Integer.valueOf(-8)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-6), Integer.valueOf(-8)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(5), Integer.valueOf(-8)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-5), Integer.valueOf(-8)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(8), Integer.valueOf(-8)), localSqlApproxNumConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(6), Integer.valueOf(-8)), localSqlApproxNumConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(7), Integer.valueOf(-8)), localSqlApproxNumConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(91), Integer.valueOf(-8)), localSqlDateTimeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(92), Integer.valueOf(-8)), localSqlDateTimeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(93), Integer.valueOf(-8)), localSqlDateTimeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(2), Integer.valueOf(-8)), localSqlExactNumberConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(3), Integer.valueOf(-8)), localSqlExactNumberConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-7), Integer.valueOf(-8)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(16), Integer.valueOf(-8)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(4), Integer.valueOf(-9)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-6), Integer.valueOf(-9)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(5), Integer.valueOf(-9)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-5), Integer.valueOf(-9)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(8), Integer.valueOf(-9)), localSqlApproxNumConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(6), Integer.valueOf(-9)), localSqlApproxNumConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(7), Integer.valueOf(-9)), localSqlApproxNumConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(91), Integer.valueOf(-9)), localSqlDateTimeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(92), Integer.valueOf(-9)), localSqlDateTimeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(93), Integer.valueOf(-9)), localSqlDateTimeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(2), Integer.valueOf(-9)), localSqlExactNumberConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(3), Integer.valueOf(-9)), localSqlExactNumberConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-7), Integer.valueOf(-9)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(16), Integer.valueOf(-9)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(4), Integer.valueOf(-10)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-6), Integer.valueOf(-10)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(5), Integer.valueOf(-10)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-5), Integer.valueOf(-10)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(8), Integer.valueOf(-10)), localSqlApproxNumConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(6), Integer.valueOf(-10)), localSqlApproxNumConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(7), Integer.valueOf(-10)), localSqlApproxNumConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(91), Integer.valueOf(-10)), localSqlDateTimeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(92), Integer.valueOf(-10)), localSqlDateTimeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(93), Integer.valueOf(-10)), localSqlDateTimeConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(2), Integer.valueOf(-10)), localSqlExactNumberConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(3), Integer.valueOf(-10)), localSqlExactNumberConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(-7), Integer.valueOf(-10)), localSqlIntegralConverterFactory);
    this.m_converterFactoryTable.put(new Pair(Integer.valueOf(16), Integer.valueOf(-10)), localSqlIntegralConverterFactory);
  }
}


/* Location:              /home/kylin/work/couchbase/Driver/CouchbaseJDBC4.jar!/com/simba/sqlengine/executor/conversions/SqlConverterGenerator.class
 * Java compiler version: 5 (49.0)
 * JD-Core Version:       0.7.1
 */