DROP TABLE IF EXISTS T1;
DROP TABLE IF EXISTS T2;

CREATE TABLE IF NOT EXISTS T1(a INT);
CREATE TABLE IF NOT EXISTS T2(b INT);

INSERT INTO T1 VALUES (1), (2), (3);
INSERT INTO T2 VALUES (2), (4);

-- inner join
SELECT * FROM T1 INNER JOIN T2 ON T1.a = T2.b;
SELECT * FROM T2 INNER JOIN T1 ON T1.a = T2.b;

-- left join
SELECT * FROM T1 LEFT OUTER JOIN T2 ON T1.a = T2.b;
SELECT * FROM T2 LEFT OUTER JOIN T1 ON T1.a = T2.b;

-- right join
SELECT * FROM T1 RIGHT OUTER JOIN T2 ON T1.a = T2.b;
SELECT * FROM T2 RIGHT OUTER JOIN T1 ON T1.a = T2.b;

-- cross join
SELECT * FROM T1 CROSS JOIN T2;
SELECT * FROM T2 CROSS JOIN T1;

SELECT * FROM T1, T2 WHERE T1.a = T2.b;
SELECT * FROM T1, T2;
