package com.simba.couchbase.exceptions;

public enum CBJDBCMessageKey
{
  CATALOGFUN_CATALOGONLY_FAIL_ERR,  CATALOGFUN_CATALOGONLY_FAIL_GEN_ERR,  CATALOGFUN_CATALOGSCHEMAONLY_FAIL_ERR,  CATALOGFUN_CATALOGSCHEMAONLY_FAIL_GEN_ERR,  CATALOGFUN_CATALOGCOLUMN_FAIL_ERR,  CATALOGFUN_CATALOGCOLUMN_FAIL_GEN_ERR,  CATALOGFUN_TABLEONLY_FAIL_ERR,  CATALOGFUN_TABLEONLY_FAIL_GEN_ERR,  CATALOGFUN_PRIMARYKEY_FAIL_GEN_ERR,  CATALOGFUN_PRIMARYKEY_NO_CATALOG_FOUND_ERR,  CATALOGFUN_PRIMARYKEY_NO_SCHEMA_FOUND_ERR,  CATALOGFUN_PRIMARYKEY_TABLE_NOT_FOUND_ERR,  CLUSTER_BAK_FETCHING_ERR,  CLUSTER_IDEN_ERR,  CONN_DEFAULT_PROP_ERR,  CONN_FAIL_ERR,  CONN_FAIL_GEN_ERR,  CONN_DISCONNECT_ERR,  CONN_CONNECT_CRED_ERR,  CONN_CONNECT_SSL_ERR,  PARAMETER_QUERY_DATA_TYPE_ERR_NON_SUPPORT_DATA_TYPE,  PARAMETER_QUERY_DATA_TYPE_ERR_INCORRECT_DATA_TYPE,  PARAMETER_QUERY_DATA_TYPE_ERR_NULL_DATA_TYPE,  PARAMETER_INPUT_VALUE_ERROR,  DATA_FETCH_INIT_ERR,  DRIVER_DEFAULT_PROP_ERR,  LICENSE_VALIDATION_ERROR,  LICENSE_FILE_READ_ERROR,  LET_CLAUSE_BUILD_ERROR_INVALID_KEYCOLUMN_SOURCENAME,  LET_CLAUSE_BUILD_ERROR_NO_TABLE_ALIAS_FOR_COLUMN,  LET_CLAUSE_BUILD_ERROR_INVALID_FLATTENED_COLUMN_SOURCENAME,  METADATA_COLUMN_NOT_FOUND,  METADATA_DATANOTSUPPORT_ERR,  METADATA_GENERATE_ERR,  N1QLCLIENT_GET_ERR,  N1QLCLIENT_POST_ERR,  N1QLCLIENT_FETCH_ERR,  PASSDOWN_BUILD_VALUEEXPR_ERROR,  QUERY_EXECUTION_FAIL_ERR,  QUERY_EXECUTION_FAIL_GEN_ERR,  QUERY_EXE_NO_KEYSPACE_ERR,  QUERY_EXE_NO_PRIMARY_INDEX_ERR,  QUERY_EXE_AUTHORIZATION_ERR,  QUERY_EXE_PREPARE_FAIL_ERR,  QUERY_EXE_PREPARE_FAIL_GEN_ERR,  QUERY_EXE_COPY_COLUMN_METADATA_ERROR,  QUERY_PREPARE_FAIL_ERR,  QUERY_PREPARE_FAIL_GEN_ERR,  QUERY_UPDATE_NO_KEYSPACE_ERR,  QUERY_UPDATE_NO_PRIMARY_INDEX_ERR,  QUERY_UPDATE_AUTHORIZATION_ERR,  QUERY_UPDATE_FAIL_GEN_ERR,  QUERY_INFO_FAIL_ERR,  SCHEMAMAP_GEN_ERROR,  SCHEMAMAP_TABLE_GEN_ERROR,  SCHEMAMAP_COLUMN_GEN_ERROR,  SCHEMAMAP_LOADING_ERROR,  SCHEMAMAP_FAILED_TO_IMPORT_ERROR,  SCHEMAMAP_LOADING_FROM_DATABASE_ERROR,  SCHEMAMAP_DELETE_ERROR,  SCHEMAMAP_MULTIPLE_CATALOGS_ERROR,  SCHEMAMAP_MULTIPLE_SCHEMAS_ERROR,  SCHEMAMAP_MISSING_FILE_ERROR,  SOURCENAME_PARSE_ERROR,  WRITE_BACK_ERROR_FAIL_WRITEBACK,  WRITE_BACK_ERROR_MISSING_COLUMN,  WRITE_BACK_ERROR_MISSING_PRIMARYKEY,  WRITE_BACK_ERROR_READONLY_COLUMN,  SCHEMAMAP_ONLY_RESULT_ERROR;
  
  private CBJDBCMessageKey() {}
}


/* Location:              /home/kylin/work/couchbase/Driver/CouchbaseJDBC4.jar!/com/simba/couchbase/exceptions/CBJDBCMessageKey.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */